# Use the official PostgreSQL base image
FROM postgres:latest

# Set environment variables for database configuration
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=secretpass
ENV POSTGRES_DB=postgres

# Expose PostgreSQL port
EXPOSE 5432

