version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: "run.py"
      FLASK_DB_TYPE: "postgres"
      FLASK_DB_USER: "postgres"
      FLASK_DB_NAME: "postgres"
      FLASK_DB_PASSWORD: "secretpass"
      FLASK_DB_HOST: "db"
      FLASK_DB_PORT: "5432"
    depends_on:
      - db
    ports:
      - "4000:4000"  
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secretpass"
      POSTGRES_DB: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        REACT_APP_BACKEND_URL: "http://localhost:4000" 
    depends_on:
      - backend
    ports:
      - "3000:80"  # Map port 80 in the container to port 3000 on the host
    restart: always

volumes:
  pgdata:
